name: Build and Deploy :3

on:
  push: { branches: [main] }
  pull_request: { types: [closed], branches: [main] }
  workflow_dispatch: {}

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-sites
  cancel-in-progress: true
# add auto build daily
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # ─────────────────────────────────────────────────── ─── ── ─
      #  🛈  Checkout, Install dependencies
      # ─────────────────────────────────────────────────── ─── ── ─
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { run_install: false }
      - uses: actions/setup-node@v4
        with: { cache: "pnpm", node-version: "20" }
      - run: pnpm install --prod --frozen-lockfile

      # ─────────────────────────────────────────────────── ─── ── ─
      #  🛈  Build and deploy to Nekoweb
      # ─────────────────────────────────────────────────── ─── ── ─
      - run: pnpm run bot:buildneko
      - name: List ^~^ website recursively
        run: |
          echo "Listing all files in ^~^ website:"
          find "^~^ website" -type f
      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './^~^ website'
          DEPLOY_DIR: '/'
          CLEANUP: 'True'
          NEKOWEB_PAGENAME: 'awasaka01'

      # ─────────────────────────────────────────────────── ─── ── ─
      #  🛈  Build with Neocities flag and deploy to Neocities
      # ─────────────────────────────────────────────────── ─── ── ─
      # - run: pnpm run bot:buildneo
      # - name: List ^~^ website recursively
      #   run: |
      #     echo "Listing all files in ^~^ website:"
      #     find "^~^ website" -type f
      # - name: Deploy to Neocities
      #   uses: bcomnes/deploy-to-neocities@v3
      #   with:
      #     api_key: ${{ secrets.NEOCITIES_API_KEY }}
      #     dist_dir: ^~^ website
      #     neocities_supporter: false
      #     preview_before_deploy: true
      #     cleanup: true