name: Build and Deploy :3

on:
  push: {}
  pull_request: { types: ["closed"] }
  workflow_dispatch: {} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # ───────────────────────────────────────────────
      #  🛈  Checkout, Install dependencies, Build
      # ───────────────────────────────────────────────
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { run_install: false }
      - uses: actions/setup-node@v4
        with: { cache: "pnpm", node-version: "20" }
      - run: pnpm install --prod --frozen-lockfile

      - run: pnpm run build --production

      # ───────────────────────────────────────────────
      #  🛈  Add build folder to commit
      # ───────────────────────────────────────────────
      - run: |
          BUILD_DIR="^~^ website"

          # Configure git
          git config user.name "rawr!"
          git config user.email "rawr@users.noreply.github.com"

          # Use a temporary git index
          TMP_INDEX=$(mktemp)
          export GIT_INDEX_FILE=$TMP_INDEX

          # Stage only the build folder
          git add -f "$BUILD_DIR"

          # Create a commit in the temporary index
          git commit -m "chore: update build folder [skip ci]"

          # Push the commit to the current branch on GitHub
          git push origin HEAD:HEAD --force-with-lease

          # Clean up temporary index
          rm -f $TMP_INDEX

      # ───────────────────────────────────────────────
      #  🛈  Deploy to Nekoweb (only on main)
      # ───────────────────────────────────────────────
      # - name: Deploy to Nekoweb
      #   if: github.ref == 'refs/heads/main'
      #   uses: mp-pinheiro/nekoweb-deploy@main
      #   with: {
      #     API_KEY: "${{ secrets.NEKOWEB_API_KEY }}",
      #     BUILD_DIR: "^~^ website",
      #     DEPLOY_DIR: "/",
      #     CLEANUP: "False",
      #     DELAY: "0.5",
      #     NEKOWEB_PAGENAME: "fairfruit",
      #     ENCRYPTION_KEY: "${{ secrets.NEKOWEB_ENCRYPTION_KEY }}"
      #   }

      # ───────────────────────────────────────────────
      #  🛈  Deploy to Neocities (only on main)
      # ───────────────────────────────────────────────
      - if: github.ref == 'refs/heads/main'
        run: pnpm run build --production --neocities

      # - if: github.ref == 'refs/heads/main'
      #   uses: bcomnes/deploy-to-neocities@v3
      #   with: {
      #     api_key: "${{ secrets.NEOCITIES_API_TOKEN }}",
      #     dist_dir: "dist",
      #     cleanup: false,
      #     neocities_supporter: false,
      #     preview_before_deploy: true
      #   }
